travis:
  secure:
    BINSTAR_TOKEN: PxD1WhATClCgh1oaWZx7Z/q3kVLB2LenEbXR1SKqK0lCwZpVzyNAebXZGEFME1p8YrFmwNoxMgRGZscilfjDA2DJDAzLliyrtFhhyRQRSOeZRmihLIXb165ZYnJexQ/Il2xIXiyHeaOzgoaVlw/xX5Pshvb5Zr5NUFyLHwGAt/FtC3RSCc4mX/my2mZDhinBa7Mrd0/hxEfDThA0bOTomQ5EqtrkpjlTDoBON1N5GITz64EGBqblg0Ju1L9PBmURaq6HEbtQhqbdNNMDAtRJ1sO9KrOKURz/yYiZcRZFGggVDl0P+PcuPInPI6WrekeImWxUcERTa6zC72tDWnUrF+I4pq3NQ1aaX2T5A/tnCnzibGJ75ejoAQuc/1qSG9XNVhLG6CGfkLwvc2KMx1dxiAnVqkOI1flSTf8LCivXajpBj/M2G5rZAevrGIJkEv/fV4CGDPuEYD4AOoT4UjvgvxFgrhdx4+Qj5ZRhRVmJ4VGyNgndVbw+X2opgfozffmkHvLnFSwUjIrlB3rfggdfmRMwp0k/6rsIkww9vQq5RJWXeCtqoB21pJudByFErhIzLXR5gNmEOqsHnQk0qsxtXqiQDOXcrgg5Bw5RQX9IPJzZtM/ez/inX68qT3HYGX1SznX4OkrytvAsF1EzuNRvNwnAIY8oyt8NB5AtXAWkriw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
